export enum NamedRoutes {
    HOME= "Home",
    REGISTER = "Register",
    LOGIN = "Login",
    LINK_INSTAGRAM = "Link instagram",
    LINK_COMPLETE = "Link Complete",
    MAINTENANCE = "Maintenance",
    NOT_FOUND = "Not found",
    ONBOARDING_PHASE_ONE = "Onboarding phase 1",
    SELECT_CREATOR_TYPE = "Select creator type",
    ONBOARDING_START = "Onboarding start",
    ONBOARDING_PHASE_TWO = "Onboarding phase 2",
    ONBOARDING_PHASE_THREE = "Onboarding phase 3",
    GENERATE_PERSONA = "Generate persona",
    CHOOSE_PERSONA = "Choose persona",
    START_PERSONA = "Start persona",
    WAITLIST = "Waitlist",
    VIEW_TOPICS = "View topics",
    VIEW_POSTS = "View posts",
    SETTINGS = "Settings",
    GENERATE_TOPICS = "Generate Topics",
    GENERATE_POSTS = "Generate Posts",
    FORGOT_PASSWORD= "Forgot password",
    UPDATE_PASSWORD= "Update password",
    POSTS_BOARD_VIEW="Board View"
}
